version: '3.1'

services:
  postgres:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: password

  go-app:
    container_name: app
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DSN: dbname=postgres user=postgres password=password host=postgres port=5432 sslmode=disable
